stages:
  - notify

telegram_notify:
  stage: notify
  image: telegram-messenger:latest
  tags: [default]
  script:
    - echo "Sending Telegram notification..."
  only:
    - branches
  except:
    - tags
  variables:
    CHAT_ID: ${DEVTEAM_ID}
    THREAD_ID: ${DEPLOY_ID}
    PUSH: "TRUE"
  when: always
